version: '2'

services:
  obm:
    image: yoff/obm:latest
    restart: on-failure
    #volumes:
    #  - ./config:/root/.obm/config
    #  - ./logs:/root/.obm/log
    #  - /BACKUPSOURCE:/BACKUPSOURCE:ro
    hostname: docker-obm
    environment:
      - TZ=America/Phoenix
      - USERNAME=jeffre
      - PASSWORD=secretpassword
      - SERVER=obsr.example.com
      - PROTO=https
      - LANG=en
      - BSET-1468557583616=PKCS7Padding,-256,,
